/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export const projectModel = {
  languages: {
    csCZ: {
      codename: 'cs-CZ',
      name: 'Czech',
    },
    enUS: {
      codename: 'en-US',
      name: 'Default project language',
    },
  },
  contentTypes: {
    article: {
      codename: 'article',
      name: 'Article',
      elements: {
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        date: {
          codename: 'date',
          name: 'Date',
        },
        tags: {
          codename: 'tags',
          name: 'Tags',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        category: {
          codename: 'category',
          name: 'Category',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    author: {
      codename: 'author',
      name: 'Author',
      elements: {
        vk: {
          codename: 'vk',
          name: 'VK',
        },
        telegram: {
          codename: 'telegram',
          name: 'Telegram',
        },
        twitter: {
          codename: 'twitter',
          name: 'Twitter',
        },
        bio: {
          codename: 'bio',
          name: 'Bio',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        avatar_image: {
          codename: 'avatar_image',
          name: 'Avatar image',
        },
        email: {
          codename: 'email',
          name: 'Email',
        },
        rss: {
          codename: 'rss',
          name: 'RSS',
        },
        github: {
          codename: 'github',
          name: 'Github',
        },
      },
    },
    category: {
      codename: 'category',
      name: 'Category',
      elements: {
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    menu: {
      codename: 'menu',
      name: 'Menu',
      elements: {
        menu_items: {
          codename: 'menu_items',
          name: 'Menu items',
        },
      },
    },
    menu_item: {
      codename: 'menu_item',
      name: 'Menu Item',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
      },
    },
    page: {
      codename: 'page',
      name: 'Page',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        meta_description: {
          codename: 'meta_description',
          name: 'Meta description',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        gatsby_template: {
          codename: 'gatsby_template',
          name: 'Gatsby template',
        },
      },
    },
    site_metadata: {
      codename: 'site_metadata',
      name: 'Site Metadata',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        domain: {
          codename: 'domain',
          name: 'Domain',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        page_not_found_message: {
          codename: 'page_not_found_message',
          name: 'Page not found message',
        },
        copyright: {
          codename: 'copyright',
          name: 'Copyright',
        },
      },
    },
    tag: {
      codename: 'tag',
      name: 'Tag',
      elements: {
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
  },
  taxonomies: {},
};
