import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Article = IContentItem<{
  slug: Elements.UrlSlugElement;
  date: Elements.DateTimeElement;
  tags: Elements.LinkedItemsElement<IContentItem>;
  content: Elements.RichTextElement;
  category: Elements.LinkedItemsElement<IContentItem>;
  description: Elements.TextElement;
  title: Elements.TextElement;
}>;
