import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Author = IContentItem<{
  vk: Elements.TextElement;
  telegram: Elements.TextElement;
  twitter: Elements.TextElement;
  bio: Elements.TextElement;
  name: Elements.TextElement;
  avatar_image: Elements.AssetsElement;
  email: Elements.TextElement;
  rss: Elements.TextElement;
  github: Elements.TextElement;
}>;
