import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.3.0-0'
 */
export type Category = IContentItem<{
  slug: Elements.UrlSlugElement;
  title: Elements.TextElement;
}>;

export const Category_CODENAME: string = "category"
