import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.3.0-0'
 */
export type Menu_item = IContentItem<{
  content: Elements.LinkedItemsElement<IContentItem>;
  slug: Elements.UrlSlugElement;
  label: Elements.TextElement;
}>;

export const Menu_item_CODENAME: string = "menu_item"
