import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type MenuItem = IContentItem<{
  content: Elements.LinkedItemsElement<IContentItem>;
  slug: Elements.UrlSlugElement;
  label: Elements.TextElement;
}>;
