import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Menu = IContentItem<{
  menu_items: Elements.LinkedItemsElement<IContentItem>;
}>;
