import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.3.0-0'
 */
export type Menu = IContentItem<{
  menu_items: Elements.LinkedItemsElement<IContentItem>;
}>;

export const Menu_CODENAME: string = "navigation_menu";