import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Page = IContentItem<{
  description: Elements.RichTextElement;
  meta_description: Elements.TextElement;
  title: Elements.TextElement;
  gatsby_template: Elements.MultipleChoiceElement;
}>;
