import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type SiteMetadata = IContentItem<{
  title: Elements.TextElement;
  domain: Elements.TextElement;
  subtitle: Elements.TextElement;
  page_not_found_message: Elements.TextElement;
  copyright: Elements.TextElement;
}>;
