import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.3.0-0'
 */
export type Site_metadata = IContentItem<{
  title: Elements.TextElement;
  domain: Elements.TextElement;
  subtitle: Elements.TextElement;
  page_not_found_message: Elements.TextElement;
  copyright: Elements.TextElement;
}>;

export const Site_metadata_CODENAME: string = "site_metadata"