import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Tag = IContentItem<{
  slug: Elements.UrlSlugElement;
  title: Elements.TextElement;
}>;
